# Generated by Django 3.0.4 on 2020-03-30 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('screenshot_url', models.CharField(blank=True, max_length=1000)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('reported_at', models.DateTimeField()),
                ('text', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('processing_result', models.CharField(choices=[('assigned', 'Przypisany'), ('duplicate', 'Duplikat')], default=None, max_length=30, null=True)),
            ],
            options={
                'db_table': 'news_draft',
            },
        ),
    ]
