# Generated by Django 3.0.4 on 2020-05-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdraft',
            name='processing_result',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('duplicate', 'Duplicate')], default=None, max_length=30, null=True),
        ),
    ]
