# Generated by Django 3.0.4 on 2020-05-15 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_auto_20200510_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
                ('source', models.TextField()),
                ('reported_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'question_draft',
            },
        ),
    ]
