variable "ecr_registry" {}
variable "ecr_registry_st" {}
variable "bucket" {}
variable "acl" {}
variable "key" {}
variable "region" {}
variable "encrypt" {}
variable "dynamodb_table" {}
variable "fqdn" {}
variable "image_tag" {}
variable "domain" {}
variable "environment" {}
variable "vpc_id" {}
variable "azs" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "certificate_arn" {}
variable "postgres_host" {}
variable "postgres_username" {}
variable "name" {}
variable "postgres_password" {}
variable "cors_allow_all" {}
variable "debug" {}
variable "schedule_expr" {}
