# Generated by Django 3.0.4 on 2020-03-26 16:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("screenshot_url", models.CharField(blank=True, max_length=1000)),
                ("reporter_email", models.EmailField(max_length=254)),
                ("reported_at", models.DateTimeField()),
                ("text", models.TextField(blank=True)),
                ("comment", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="FactCheckerOpinion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("true", "Verified True"),
                            ("false", "Verified False"),
                            ("spam", "Verified Spam"),
                            ("unidentified", "Cannot be verified"),
                        ],
                        default="unidentified",
                        max_length=50,
                    ),
                ),
                ("title", models.TextField()),
                ("comment", models.TextField(blank=True)),
                ("confirmation_sources", models.TextField(blank=True)),
                ("about_corona_virus", models.BooleanField(default=True)),
                ("is_duplicate", models.BooleanField(default=False)),
                ("duplicate_url", models.URLField(blank=True, max_length=2000)),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factcheckeropinion_set",
                        related_query_name="factcheckeropinion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factcheckeropinion_set",
                        related_query_name="factcheckeropinion",
                        to="news.News",
                    ),
                ),
            ],
            options={
                "db_table": "fact_checker_opinion",
                "abstract": False,
                "unique_together": {("news", "judge")},
            },
        ),
        migrations.CreateModel(
            name="ExpertOpinion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("true", "Verified True"),
                            ("false", "Verified False"),
                            ("spam", "Verified Spam"),
                            ("unidentified", "Cannot be verified"),
                        ],
                        default="unidentified",
                        max_length=50,
                    ),
                ),
                ("title", models.TextField()),
                ("comment", models.TextField(blank=True)),
                ("confirmation_sources", models.TextField(blank=True)),
                ("about_corona_virus", models.BooleanField(default=True)),
                ("is_duplicate", models.BooleanField(default=False)),
                ("duplicate_url", models.URLField(blank=True, max_length=2000)),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertopinion_set",
                        related_query_name="expertopinion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertopinion_set",
                        related_query_name="expertopinion",
                        to="news.News",
                    ),
                ),
            ],
            options={
                "db_table": "expert_opinion",
                "abstract": False,
                "unique_together": {("news", "judge")},
            },
        ),
    ]
