# Generated by Django 3.0.4 on 2020-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertopinion',
            name='duplicate_reference',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factcheckeropinion',
            name='duplicate_reference',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
