# Generated by Django 3.0.4 on 2020-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200410_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertopinion',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='expertopinion',
            name='confirmation_sources',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='expertopinion',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='expertopinion',
            name='verdict',
            field=models.CharField(blank=True, choices=[('true', 'Verified True'), ('false', 'Verified False'), ('spam', 'Verified Spam'), ('unidentified', 'Cannot be verified')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='factcheckeropinion',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='factcheckeropinion',
            name='confirmation_sources',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='factcheckeropinion',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='factcheckeropinion',
            name='verdict',
            field=models.CharField(blank=True, choices=[('true', 'Verified True'), ('false', 'Verified False'), ('spam', 'Verified Spam'), ('unidentified', 'Cannot be verified')], default='', max_length=50),
        ),
    ]
