# Generated by Django 3.0.4 on 2020-05-19 06:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200421_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_domain', to='news.Domain')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_domain', to='news.News')),
            ],
            options={
                'unique_together': {('news', 'domain')},
            },
        ),
        migrations.AddField(
            model_name='news',
            name='domains',
            field=models.ManyToManyField(related_name='news', through='news.NewsDomain', to='news.Domain'),
        ),
    ]
