# Generated by Django 3.0.4 on 2020-06-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200525_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssensitivekeyword',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_sensitive_keyword', to='news.News'),
        ),
    ]
