# Generated by Django 3.0.4 on 2020-06-10 10:58

from django.db import migrations, models
from django.db.models import Q


def set_is_published_for_news_with_expert_opinion(apps, schema_editor):
    News = apps.get_model('news', 'news')
    News.objects.all().prefetch_related(
        "expertopinion"
    ).exclude(
        Q(
            Q(expertopinion__isnull=True)
            | Q(deleted=True)
        )
    ).update(is_published=True)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200602_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_is_published_for_news_with_expert_opinion),
    ]
