# Generated by Django 3.0.4 on 2020-06-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_news_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='origin',
            field=models.CharField(choices=[('plugin', 'Plugin'), ('chatbot', 'Chatbot'), ('mobile', 'Mobile')], default='plugin', max_length=30),
        ),
    ]
