# Generated by Django 3.0.4 on 2020-06-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_news_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertopinion',
            name='about_corona_virus',
        ),
        migrations.RemoveField(
            model_name='factcheckeropinion',
            name='about_corona_virus',
        ),
    ]
