# Generated by Django 3.0.4 on 2020-03-30 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200330_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('base_user', 'Base User'), ('fact_checker', 'Fact Checker'), ('expert', 'Expert'), ('admin', 'Admin')], default='fact_checker', max_length=30),
        ),
        migrations.AlterField(
            model_name='usernews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernews_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
