# Generated by Django 3.0.4 on 2020-03-31 10:09

from django.db import migrations
import dook.core.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200330_1603'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', dook.core.users.managers.UserManager()),
                ('fact_checkers', dook.core.users.managers.FactCheckersManager()),
            ],
        ),
    ]
