# Generated by Django 3.0.4 on 2020-04-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200331_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('Błąd wysyłki', 'FAILED'), ('Oczekujące', 'WAITING'), ('W trakcie', 'IN_PROGRESS'), ('Wykorzystane', 'USED')], default='Oczekujące', max_length=30),
        ),
    ]
