# Generated by Django 3.0.4 on 2020-05-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200519_0617'),
        ('users', '0009_auto_20200510_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Domain'),
        ),
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Domain'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='user_role',
            field=models.CharField(choices=[('fact_checker', 'Fact Checker'), ('specialist', 'Specialist'), ('expert', 'Expert')], default='fact_checker', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('base_user', 'Base User'), ('fact_checker', 'Fact Checker'), ('specialist', 'Specialist'), ('expert', 'Expert'), ('admin', 'Admin')], default='fact_checker', max_length=30),
        ),
    ]
