# Generated by Django 3.0.4 on 2020-05-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200519_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernews',
            name='assigned_by_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
