# Generated by Django 3.0.4 on 2020-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usernews_assigned_by_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_subscriptions',
            field=models.BooleanField(default=True),
        ),
    ]
