# Generated by Django 3.0.4 on 2020-06-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_allow_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='user_role',
            field=models.CharField(choices=[('fact_checker', 'Fact Checker'), ('specialist', 'Specialist'), ('expert', 'Expert'), ('moderator', 'Moderator')], default='fact_checker', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('base_user', 'Base User'), ('fact_checker', 'Fact Checker'), ('specialist', 'Specialist'), ('expert', 'Expert'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='fact_checker', max_length=30),
        ),
    ]
