# Generated by Django 3.0.4 on 2020-07-08 10:32

from django.db import migrations, models


def fix_invitation_status_names(apps, schema_editor):
    status_mapping = {
        "Błąd wysyłki": "failed",
        "Oczekujące": "waiting",
        "W trakcie": "in_progress",
        "Wykorzystane": "used",
        "Failed": "failed",
        "Waiting": "waiting",
        "In progress": "in_progress",
        "Used": "used",
    }

    Invitation = apps.get_model('users', 'invitation')

    for k, v in status_mapping.items():
        Invitation.objects.filter(status=k).update(status=v)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200612_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('failed', 'FAILED'), ('waiting', 'WAITING'), ('in_progress', 'IN_PROGRESS'), ('used', 'USED')], default='waiting', max_length=30),
        ),
        migrations.RunPython(fix_invitation_status_names),
    ]
